add_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: sensor
          integration: freezer_management
    item:
      required: true
      selector:
        text:
    packagingType:
      selector:
        text:
    freezerCompartment:
      selector:
        text:
    storageDate:
      selector:
        text:

remove_item:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: sensor
          integration: freezer_management
    itemId:
      required: true
      selector:
        text:

clear_inventory:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: sensor
          integration: freezer_management
